# Generated by Django 3.2.8 on 2021-10-12 20:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('proj_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('repo_link', models.URLField()),
                ('proj_link', models.URLField()),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'project',
            },
        ),
    ]
